# Generated by Django 5.0.14 on 2026-10-03 01:35

import accounts.models
import config.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, db_index=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('profile_type', models.CharField(choices=[('STUDENT', 'Étudiant'), ('PHYSIOTHERAPIST', 'Kinésithérapeute')], max_length=20)),
                ('role', models.CharField(choices=[('STUDENT', 'Étudiant'), ('PHYSIOTHERAPIST', 'Kinésithérapeute'), ('INSTRUCTOR', 'Formateur'), ('CONTENT_EDITOR', 'Éditeur de contenu'), ('ADMIN', 'Administration'), ('SUPER_ADMIN', 'Administration principale')], default='PHYSIOTHERAPIST', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Actif'), ('suspended', 'Suspendu'), ('pending', 'En attente')], default='active', max_length=12)),
                ('email_verified', models.BooleanField(default=False)),
                ('locale', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], default='fr', max_length=2)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('premium', models.BooleanField(default=False)),
                ('newsletter', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'membre',
                'verbose_name_plural': 'membres',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PhysiotherapistProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prof_status', models.CharField(blank=True, max_length=80)),
                ('workplace', models.CharField(blank=True, max_length=200)),
                ('experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=80)),
                ('website', models.URLField(blank=True, max_length=300)),
                ('linkedin', models.URLField(blank=True, max_length=300)),
                ('expertise', config.models.StringListField()),
                ('languages', config.models.StringListField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='physiotherapist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil kinésithérapeute',
                'verbose_name_plural': 'profils kinésithérapeute',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('academic_year', models.CharField(blank=True, max_length=40)),
                ('graduation_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('interests', config.models.StringListField()),
                ('languages', config.models.StringListField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil étudiant',
                'verbose_name_plural': 'profils étudiant',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_new_resources', models.BooleanField(default=True)),
                ('notif_new_courses', models.BooleanField(default=True)),
                ('notif_webinars', models.BooleanField(default=True)),
                ('notif_newsletter', models.BooleanField(default=False)),
                ('notif_product', models.BooleanField(default=True)),
                ('public_profile', models.BooleanField(default=False)),
                ('show_email', models.BooleanField(default=False)),
                ('allow_analytics', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférences du membre',
                'verbose_name_plural': 'préférences des membres',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='user_role_status_idx'),
        ),
    ]
