# Generated by Django 5.0.14 on 2026-10-03 01:35

import config.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('price_dzd', models.PositiveIntegerField(default=0)),
                ('interval', models.CharField(choices=[('free', 'Gratuit'), ('month', 'Mensuel'), ('year', 'Annuel'), ('quote', 'Sur devis')], default='month', max_length=8)),
                ('audience', models.CharField(choices=[('all', 'Tous'), ('STUDENT', 'Étudiants'), ('PHYSIOTHERAPIST', 'Kinésithérapeutes')], default='all', max_length=20)),
                ('features', config.models.StringListField()),
                ('limits', models.TextField(blank=True, help_text='Ce que la formule ne couvre pas.')),
                ('premium', models.BooleanField(default=False, help_text="Ouvre l'accès aux contenus premium.")),
                ('highlighted', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "formule d'abonnement",
                'verbose_name_plural': "formules d'abonnement",
                'ordering': ['order', 'price_dzd', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('inactive', 'Inactif'), ('pending', 'En attente'), ('active', 'Actif'), ('rejected', 'Refusé'), ('cancelled', 'Résilié'), ('expired', 'Expiré')], db_index=True, default='inactive', max_length=12)),
                ('motivation', models.TextField(blank=True, help_text='Motif de la demande.')),
                ('promo_code', models.CharField(blank=True, max_length=40)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_decisions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'abonnement',
                'verbose_name_plural': 'abonnements',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscription_user_idx')],
            },
        ),
    ]
