# Generated by Django 5.0.14 on 2026-10-06 21:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceKeyPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('trending', 'Progression'), ('activity', 'Mesure'), ('target', 'Objectif'), ('brain', 'Dimension psychologique'), ('shield', 'Sécurité'), ('check', 'Critère'), ('clock', 'Délai'), ('dumbbell', 'Renforcement')], default='check', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_point_set', to='content.resource')),
            ],
            options={
                'verbose_name': 'point clé',
                'verbose_name_plural': 'points clés',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation', models.CharField(help_text="Auteurs, année et titre de l'article.", max_length=400)),
                ('source', models.CharField(blank=True, help_text='Revue, volume, pages.', max_length=300)),
                ('url', models.URLField(blank=True, max_length=600)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_set', to='content.resource')),
            ],
            options={
                'verbose_name': 'référence',
                'verbose_name_plural': 'références',
                'ordering': ['position'],
            },
        ),
    ]
