# Generated by Django 5.0.14 on 2026-10-03 01:35

import config.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('university', 'Université'), ('hospital', 'Établissement de santé'), ('society', 'Société savante'), ('company', 'Entreprise')], default='university', max_length=20)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'partenaire',
                'verbose_name_plural': 'partenaires',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Vide : diffusé dès maintenant.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vide : sans date de fin.', null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage, croissant.")),
                ('placement', models.CharField(choices=[('home_hero', 'Accueil — carrousel principal'), ('home_featured', 'Accueil — rayons mis en avant'), ('home_career', 'Accueil — parcours par spécialité'), ('library_top', 'Bibliothèque — en tête de liste'), ('courses_top', 'Formations — en tête de liste'), ('search_top', 'Recherche — en tête de résultats')], db_index=True, default='home_featured', max_length=24)),
                ('key', models.SlugField(help_text="Identifiant stable, servant d'onglet (sport, neurologie…).", max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_href', models.CharField(blank=True, max_length=500)),
                ('section', models.CharField(blank=True, help_text='resources, courses, webinars, tools, exercises, pathologies.', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Sélection manuelle'), ('popular', 'Les plus consultés'), ('newest', 'Les plus récents')], default='manual', max_length=10)),
                ('limit', models.PositiveSmallIntegerField(default=6)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filtres d\'une source automatique : {"specialty": ["sport"]}.')),
            ],
            options={
                'verbose_name': 'rayon',
                'verbose_name_plural': 'rayons',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ShelfItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'entrée de rayon',
                'verbose_name_plural': 'entrées de rayon',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Sponsorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Vide : diffusé dès maintenant.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vide : sans date de fin.', null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage, croissant.")),
                ('placement', models.CharField(choices=[('home_hero', 'Accueil — carrousel principal'), ('home_featured', 'Accueil — rayons mis en avant'), ('home_career', 'Accueil — parcours par spécialité'), ('library_top', 'Bibliothèque — en tête de liste'), ('courses_top', 'Formations — en tête de liste'), ('search_top', 'Recherche — en tête de résultats')], db_index=True, default='library_top', max_length=24)),
                ('section', models.CharField(help_text='Section du contenu poussé.', max_length=20)),
                ('slug', models.SlugField(help_text='Slug du contenu poussé.', max_length=200)),
                ('label', models.CharField(default='Sponsorisé', help_text='Mention affichée sur la carte. Jamais masquée.', max_length=40)),
                ('note', models.CharField(blank=True, help_text='Accroche courte, sous le titre.', max_length=200)),
                ('weight', models.PositiveSmallIntegerField(default=10, help_text='Le plus lourd passe devant ; `position` départage.')),
                ('audience_filters', config.models.StringListField(help_text='Vide : tous les visiteurs. Sinon, slugs de taxonomie ciblés.')),
                ('impressions', models.PositiveIntegerField(default=0, editable=False)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'contenu sponsorisé',
                'verbose_name_plural': 'contenus sponsorisés',
                'ordering': ['-weight', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, help_text='Vide : diffusé dès maintenant.', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vide : sans date de fin.', null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage, croissant.")),
                ('placement', models.CharField(choices=[('home_hero', 'Accueil — carrousel principal'), ('home_featured', 'Accueil — rayons mis en avant'), ('home_career', 'Accueil — parcours par spécialité'), ('library_top', 'Bibliothèque — en tête de liste'), ('courses_top', 'Formations — en tête de liste'), ('search_top', 'Recherche — en tête de résultats')], db_index=True, default='home_hero', max_length=24)),
                ('theme', models.CharField(choices=[('brand', 'Marque (turquoise)'), ('dark', 'Sombre'), ('sand', 'Sable'), ('mint', 'Menthe'), ('slate', 'Ardoise')], default='brand', max_length=12)),
                ('eyebrow', models.CharField(blank=True, help_text='Surtitre court, au-dessus du titre.', max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=400)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_href', models.CharField(blank=True, help_text='Chemin interne sans préfixe de langue (/bibliotheque), ou URL complète.', max_length=500)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='promotions.partner')),
            ],
            options={
                'verbose_name': 'bannière',
                'verbose_name_plural': 'bannières',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('placement', 'key'), name='shelf_unique_key_per_placement'),
        ),
        migrations.AddField(
            model_name='shelfitem',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='promotions.shelf'),
        ),
        migrations.AddField(
            model_name='sponsorship',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsorships', to='promotions.partner'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['placement', 'active'], name='banner_placement_idx'),
        ),
        migrations.AddConstraint(
            model_name='shelfitem',
            constraint=models.UniqueConstraint(fields=('shelf', 'section', 'slug'), name='shelfitem_unique'),
        ),
        migrations.AddIndex(
            model_name='sponsorship',
            index=models.Index(fields=['placement', 'active'], name='sponsor_placement_idx'),
        ),
        migrations.AddConstraint(
            model_name='sponsorship',
            constraint=models.UniqueConstraint(fields=('placement', 'section', 'slug'), name='sponsorship_unique'),
        ),
    ]
