# Generated by Django 5.0.14 on 2026-10-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='theme',
            field=models.CharField(choices=[('brand', 'Marque (turquoise)'), ('dark', 'Sombre'), ('light', 'Clair (texte sombre)'), ('sand', 'Sable'), ('mint', 'Menthe'), ('slate', 'Ardoise')], default='brand', max_length=12),
        ),
    ]
