# Generated by Django 5.0.14 on 2026-10-03 01:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyRegion',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'région anatomique',
                'verbose_name_plural': 'régions anatomiques',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceCategory',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'catégorie de ressource',
                'verbose_name_plural': 'catégories de ressource',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name': 'spécialité',
                'verbose_name_plural': 'spécialités',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('slug', models.SlugField(max_length=96, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'mot-clé',
                'verbose_name_plural': 'mots-clés',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='TermLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('locale', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('ar', 'العربية')], max_length=2)),
                ('label', models.CharField(max_length=200)),
                ('body_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomies.bodyregion')),
                ('resource_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomies.resourcecategory')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='taxonomies.specialty')),
            ],
            options={
                'verbose_name': 'libellé de taxonomie',
                'verbose_name_plural': 'libellés de taxonomie',
            },
        ),
        migrations.AddConstraint(
            model_name='termlabel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('body_region__isnull', False), ('resource_category__isnull', True), ('specialty__isnull', True)), models.Q(('body_region__isnull', True), ('resource_category__isnull', True), ('specialty__isnull', False)), models.Q(('body_region__isnull', True), ('resource_category__isnull', False), ('specialty__isnull', True)), _connector='OR'), name='termlabel_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='termlabel',
            constraint=models.UniqueConstraint(fields=('locale', 'body_region'), name='termlabel_unique_region'),
        ),
        migrations.AddConstraint(
            model_name='termlabel',
            constraint=models.UniqueConstraint(fields=('locale', 'specialty'), name='termlabel_unique_specialty'),
        ),
        migrations.AddConstraint(
            model_name='termlabel',
            constraint=models.UniqueConstraint(fields=('locale', 'resource_category'), name='termlabel_unique_category'),
        ),
    ]
